---
- name: "Download Kibana rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elk_stack_version }}-amd64.deb"
    dest: "/tmp/kibana-{{ elk_stack_version }}-amd64.deb"
  register: download_kibana
  delegate_to: localhost
  until: download_kibana is succeeded
  when: kibana_install_type == 'remote'
