---
- name: "Download Filebeat rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-x86_64.deb"
    dest: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.deb"
  register: download_filebeat
  delegate_to: localhost
  until: download_filebeat is succeeded
  when: filebeat_install_type == 'remote'